### ISSUE TITLE
Feature request for per orbit counts

### ISSUE THREAD

**Issue by jikrant3** [prajwel/curvit#11]
Presently, curvit requires bins of particular seconds for generating lightcurve.

1) I request a way to get counts per orbit. This is particularly useful for variables witch have larger periods or observations that were done over multiple epochs. 

In the present version, if we give a 500s bin, some counts before/after the bin may be ignored due to incomplete coverage, or an orbit with ~400 s is/should be ignored.
With the proposed approach, the bins will be equal to orbits, so all the events are utilized.

2) Currently, there are no errors (~ binwidth/2) in the time values. If you add the per orbit counts, you should also add the error/width of each data point in the output file.

**Comment by prajwel** [comment]
Hi @jikrant3, thank you for your suggestions. I will try to find a way to incorporate item 1 as a feature. I think item 2 may not be required if item 1 is implemented (also, the errors will be very high if there the bin has little-time/few-counts, and such data points should not be used).

**Comment by prajwel** [comment]
Hi @jikrant3, A new function, [curve_orbitwise](https://curvit.readthedocs.io/en/latest/api/curve_orbitwise.html), has been added. It can be used to create a light curve for a source, generating one data point per orbit. I am closing this issue since the feature has been realised. Please let me know if you face any bugs.
